name: Android API Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29, 30]  # Specify the API levels available
        abi: [x86, x86_64]    # Emulator architectures

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Set up Emulator Path
        run: echo "PATH=$PATH:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Kill Any Existing Emulator
        run: |
          adb devices | grep 'emulator' | while read -r line; do adb -s $(echo $line | awk '{print $1}') emu kill; done
          adb kill-server

      - name: Install Emulator
        run: |
          sdkmanager "system-images;android-${{ matrix.api-level }};google_apis;${{ matrix.abi }}"
          sdkmanager --licenses

      - name: Verify Emulator Installation
        run: sdkmanager --list

      - name: Create and Start Emulator
        run: |
          avdmanager create avd -n test -k "system-images;android-${{ matrix.api-level }};google_apis;${{ matrix.abi }}" -d "Nexus 6" --force
          nohup emulator -avd test -no-snapshot-save -no-window -gpu swiftshader_indirect -no-audio > emulator.log 2>&1 &
          sleep 60
          cat emulator.log

      - name: Wait for Emulator to Boot
        run: |
          boot_completed=false
          timeout=0
          while [ "$boot_completed" != "1" ] && [ $timeout -lt 1800 ]; do
            boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed | tr -d '\r')
            sleep 10
            timeout=$((timeout + 10))
          done
          if [ "$boot_completed" != "1" ]; then
            echo "Emulator failed to boot in time"
            exit 1
          fi

      - name: Check Emulator Status
        run: adb -s emulator-5554 shell getprop

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

      - name: Kill Emulator
        run: adb -s emulator-5554 emu kill

      - name: Test API Integration
        run: |
          curl -X GET "https://api.calorieninjas.com/" \
          -H "Authorization: Bearer "24Dq75ydbIBCI6KpY2+BeQ==SJTYu7ebGCugjYj5" \
          -H "Content-Type: application/json"
