name: Android API Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29, 30, 31] # Android API levels for testing
        abi: [x86, x86_64]      # Emulator architectures

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Install Emulator
        run: |
          sdkmanager "system-images;android-${{ matrix.api-level }};google_apis;${{ matrix.abi }}"
          sdkmanager --licenses

      - name: Create and Start Emulator
        run: |
          avdmanager create avd -n test -k "system-images;android-${{ matrix.api-level }};google_apis;${{ matrix.abi }}" -d "Nexus 6" --force
          emulator -avd test -no-window -noaudio -no-boot-anim &

      - name: Wait for Emulator to Boot
        run: |
          boot_completed=false
          timeout=0
          while [ "$boot_completed" != "1" ] && [ $timeout -lt 600 ]; do
            boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed | tr -d '\r')
            sleep 10
            timeout=$((timeout + 10))
          done
          if [ "$boot_completed" != "1" ]; then
            echo "Emulator failed to boot in time"
            exit 1
          fi

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

      - name: Kill Emulator
        run: adb -s emulator-5554 emu kill

      - name: Test API Integration
        run: |
          curl -X GET "https://api.calorieninjas.com/" \
          -H "Authorization: Bearer 24Dq75ydbIBCI6KpY2+BeQ==SJTYu7ebGCugjYj5" \
          -H "Content-Type: application/json"
