name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29, 30, 31]
        abi: [x86, x86_64]
        device: [Nexus 6]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Install Emulator
        run: |
          if [ "${{ matrix.api-level }}" == "31" ]; then
            sdkmanager "system-images;android-31;google_apis;x86_64"
          else
            sdkmanager "system-images;android-${{ matrix.api-level }};google_apis;${{ matrix.abi }}"
          fi
          sdkmanager --licenses

      - name: Install Android SDK Tools
        run: |
          sdkmanager --install "platform-tools"

      - name: Create and Start Emulator
        run: |
          avdmanager create avd -n test -k "system-images;android-${{ matrix.api-level }};google_apis;${{ matrix.abi }}" -d "${{ matrix.device }}" --force
          emulator-headless -avd test -no-window -noaudio -no-boot-anim &

      - name: Wait for Emulator to Boot
        run: |
          boot_completed=false
          timeout=0
          while [ "$boot_completed" != "1" ] && [ $timeout -lt 600 ]; do
            boot_completed=$(adb -s emulator-5554 shell getprop sys.boot_completed | tr -d '\r')
            sleep 10
            timeout=$((timeout + 10))
          done
          if [ "$boot_completed" != "1" ]; then
            echo "Emulator failed to boot in time"
            exit 1
          fi

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run Tests
        run: ./gradlew connectedAndroidTest

      - name: Kill Emulator
        run: adb -s emulator-5554 emu kill
