name: Android Back Button Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29, 30]  # Specify API levels available
        abi: [x86, x86_64]    # Emulator architectures

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Set up Emulator Path
        run: echo "PATH=$PATH:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Install Emulator
        run: |
          sdkmanager "system-images;android-${{ matrix.api-level }};google_apis;${{ matrix.abi }}"
          sdkmanager --licenses

      - name: Create and Start Emulator
        run: |
          avdmanager create avd -n test -k "system-images;android-${{ matrix.api-level }};google_apis;${{ matrix.abi }}" -d "Nexus 6" --force
          nohup emulator -avd test -no-snapshot-save -no-window -gpu swiftshader_indirect -no-audio &

      - name: Wait for Emulator to Boot
        run: |
          boot_completed=false
          timeout=0
          while [ "$boot_completed" != "1" ] && [ $timeout -lt 3600 ]; do
            boot_completed=$(adb devices | grep emulator | awk '{print $1}')
            if [ -z "$boot_completed" ]; then
              echo "No emulator found. Waiting for emulator to start..."
            else
              boot_completed=$(adb -s "$boot_completed" shell getprop sys.boot_completed | tr -d '\r')
              echo "Boot status: $boot_completed. Time elapsed: $timeout seconds."
            fi
            sleep 10
            timeout=$((timeout + 10))
          done
          if [ "$boot_completed" != "1" ]; then
            echo "Emulator failed to boot in time"
            exit 1
          fi

      - name: Run Instrumented Tests
        run: ./gradlew connectedAndroidTest

      - name: Kill Emulator
        run: adb -s emulator-5554 emu kill
